# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java-CI-for-auto-upload-docker-image

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      USERNAME: smaks
      IMAGE_NAME: gateway
      run: VERSION="./gradlew version -q"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Version
        run: echo "${VERSION}"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{env.USERNAME}}
          password: '${{secrets.DOCKERHUB_PASSWORD}}'
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{env.USERNAME}}/${{env.IMAGE_NAME}}:0.0.2"